[build]
builder = "nixpacks"
buildCommand = "./gradlew :fineract-provider:build -x test -x cucumber -x spotlessCheck -x rat --no-daemon"
startCommand = "java $JAVA_OPTS -Dspring.profiles.active=basicauth,railway -Dspring.config.additional-location=classpath:/,file:config/railway/ -jar fineract-provider/build/libs/fineract-provider-*-SNAPSHOT.jar"

[deploy]
healthcheckPath = "/fineract-provider/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
