= Secrets

TBD

== Infrastructure Team

A couple of secrets for third party services are automatically configured by the infrastructure team at The Apache Foundation for the Fineract Github account. At the moment this includes environment variables for:

* Github token (e. g. to publish Github Pages, use the Github API in Github Actions)
* Docker Hub token (to publish our Docker images)
* Sonar Cloud token (for our code quality reports)

See also:

* https://infra.apache.org/github-pages.html
* https://cwiki.apache.org/confluence/display/INFRA/Github+Actions+to+DockerHub
* https://github.com/apache/jmeter-site-preview
* https://github.com/apache/fineract-site
* https://github.com/apache/systemds-website/blob/main/.asf.yaml

== Lastpass

It seems that Apache has some kind of org account or similar. Popped up a couple of times in the infrastructure documentation.

TBD

== 1Password

Other Fineract development related secrets, e. g. for deployments of demo systems on Google Cloud, AWS etc. are managed in a team account at 1Password. At the moment the following committers are members of the 1Password team account:

* mailto:edcable@apache.org[Ed Cable]
* mailto:vorburger@apache.org[Michael Vorburger]
* mailto:ptuomola@apache.org[Petri Tuomola]
* mailto:arnold@apache.org[Arnold Galovics]
* mailto:aleks@apache.org[Aleksandar Vidakovic]

NOTE: If you need access or have any questions related to those secrets then please reach out to one of the team members.
