= Step 4: Freeze JIRA

== Description

You first need to close the release in JIRA so that the about to be released version cannot be used as "fixVersion" for new bugs anymore.

https://issues.apache.org/jira/plugins/servlet/project-config/FINERACT/administer-versions?status=released-unreleased[Click this link] or go to JIRA "Administer project" page and follow "Versions" in left menu.

A form to add new releases and a table with list of all releases should appear. First, create the _next_ release. Enter that version number in the form and click "Add".

Next, in the "Actions" column in the table, click on ⋯  (three horizontal dots menu) to the right of release {version}. Choose "Release". Enter the current date (doesn't need to be the date the release is acutally announced).

TIP: For the "Unresolved Issues" radio button: If unresolved issues block the release, ignore them and proceed. If they'll be part of another release, move them to that version.

== Gradle Task

.Command
[source,bash]
----
./gradlew fineractReleaseStep4
----

CAUTION: This task is not yet automated!
