= Step 3: Create Release Branch

== Description

Communicate with the community. You do not need to start a new email thread on the developer mailing list to notify that you are about to branch, just do it ca. 2 weeks after the initial email, or later, based on the discussion on the initial email.

You do not need to ask committers to hold off any commits until you have branched finished, as it's always possible to fast-forward the branch to latest develop, or cherry-pick last minute changes to it. People should be able to continue working on the develop branch on bug fixes and great new features for the next release while the release process for the current release is being worked through.

1. Clone fresh repository copy
+
[source,bash]
----
% git clone git@github.com:apache/fineract.git
% cd fineract
----

2. Check that current HEAD points to commit on which you want to base new  release branch. Checkout a particular earlier commit if not.
+
[source,bash]
----
% git log <1>
----
<1> Check current branch history. HEAD should point to commit that you want to be base for your release branch

3. Create a new release branch with name "$Version"
+
[source,bash,subs="attributes+,+macros"]
----
% git checkout -b {revnumber}
----

4. Push new branch to Apache Fineract repository
+
[source,bash,subs="attributes+,+macros"]
----
% git push origin {revnumber}
----

5. Add new release notes in Release Folders. The change list can be swiped from the JIRA release note tool (use the "text" format for the change log). See JIRA Cleanup above to ensure that the release notes generated by this tool are what you are expecting.

6. Send en email announcing the new release branch on the earlier email thread
+
[source,text]
----
include::{rootdir}/buildSrc/src/main/resources/email/release.step03.branch.subject.ftl[lines=21..]

include::{rootdir}/buildSrc/src/main/resources/email/release.step03.branch.message.ftl[lines=21..]
----

== Gradle Task

.Command
[source,bash,subs="attributes+,+macros"]
----
% ./gradlew fineractReleaseStep3 -Pfineract.release.date="Monday, May 10, 2022" -Pfineract.release.version={revnumber}
----
