@startsalt
{
    {T
    + custom
    ++ acme
    +++ note
    ++++ core
    +++++ src
    ++++++ main
    +++++++ java
    ++++++++ com.acme.fineract.note.core
    +++++++++ data
    ++++++++++ MyData.java
    +++++++++ service
    ++++++++++ MyCustomService.java
    +++++ build.gradle
    +++++ dependencies.gradle
    ++++ service
    +++++ src
    ++++++ main
    +++++++ java
    ++++++++ com.acme.fineract.note.service
    +++++++++ AcmeNoteReadService.java
    +++++++++ AcmeNoteWriteService.java
    +++++ build.gradle
    +++++ dependencies.gradle
    ++++ starter
    +++++ src
    ++++++ main
    +++++++ java
    ++++++++ com.acme.fineract.note.starter
    +++++++++ AcmeNoteAutoConfiguration.java
    +++++ resources
    ++++++ META-INF
    +++++++ spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
    +++++ build.gradle
    +++++ dependencies.gradle
    }
}
@endsalt