server:
  port: 9008
spring:
  application:
    name: loaning-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fineract_loaning
    username: postgres
    password: vakporize
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:provider_disables_autocommit: true
  cloud:
    consul:
      discovery:
        register: true

fineract:
  url: http://localhost:8080/fineract-provider/api/v1

loan:
  events:
    exchange:
    routing:
      created: loan.created
      approved: loan.approved
      disbursed: loan.disbursed
      repayment: loan.repayment

