/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.fineract.portfolio.workingcapitalloan.domain;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import org.apache.fineract.portfolio.loanaccount.domain.LoanTransactionType;
import org.apache.fineract.portfolio.workingcapitalloan.repository.WorkingCapitalLoanTransactionRepository;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;

/**
 * Domain-level lookup facade for {@link WorkingCapitalLoanTransaction}s of a given {@link WorkingCapitalLoan}.
 *
 * <p>
 * Unlike {@code Loan}, a {@code WorkingCapitalLoan} does not hold its transactions in an in-memory collection, so the
 * equivalent of the entity's {@code findChargedOffTransaction()} / {@code getLastUserTransaction()} lookups cannot live
 * on the entity. This facade centralizes those repository-backed searches so callers do not re-implement the (type,
 * reversed, ordering) filters by hand. It returns domain entities, as opposed to
 * {@code WorkingCapitalLoanTransactionReadPlatformService}, which returns API {@code *Data} DTOs.
 * </p>
 */
@Service
@RequiredArgsConstructor
public class WorkingCapitalLoanTransactionFinder {

    /**
     * Transaction types generated by the system (Close of Business), which do not count as user activity when looking
     * for the last user-initiated transaction.
     */
    private static final List<LoanTransactionType> SYSTEM_GENERATED_TYPES = List.of(LoanTransactionType.ACCRUAL,
            LoanTransactionType.DISCOUNT_FEE_AMORTIZATION, LoanTransactionType.DISCOUNT_FEE_AMORTIZATION_ADJUSTMENT);

    private final WorkingCapitalLoanTransactionRepository transactionRepository;

    /**
     * Returns the non-reversed charge-off transaction of the loan, if any. Mirrors
     * {@code Loan#findChargedOffTransaction()} (non-reversed transaction of type
     * {@link LoanTransactionType#CHARGE_OFF}).
     */
    public Optional<WorkingCapitalLoanTransaction> findChargedOffTransaction(final WorkingCapitalLoan loan) {
        return findLatestActiveTransactionOfType(loan, LoanTransactionType.CHARGE_OFF);
    }

    /**
     * Returns the last non-reversed, user-initiated transaction of the loan, if any. Mirrors
     * {@code Loan#getLastUserTransaction()}: system-generated postings (accrual and discount-fee amortization) are
     * excluded, and the result is the latest one in (transaction date, id) order.
     */
    public Optional<WorkingCapitalLoanTransaction> getLastUserTransaction(final WorkingCapitalLoan loan) {
        return transactionRepository.findActiveExcludingTypesOrderByDateDesc(loan.getId(), SYSTEM_GENERATED_TYPES, PageRequest.of(0, 1)) //
                .stream().findFirst();
    }

    /**
     * Returns the date of the last non-reversed, user-initiated transaction of the loan, if any. This deliberately
     * ignores system-generated postings (accrual, discount-fee amortization), so that a Close of Business run cannot
     * push the date forward when there was no user activity. Mirrors {@code Loan#getLastUserTransactionDate()}.
     */
    public Optional<LocalDate> getLastUserTransactionDate(final WorkingCapitalLoan loan) {
        return getLastUserTransaction(loan).map(WorkingCapitalLoanTransaction::getTransactionDate);
    }

    /**
     * Returns the most recent non-reversed transaction of the given type, if any.
     */
    private Optional<WorkingCapitalLoanTransaction> findLatestActiveTransactionOfType(final WorkingCapitalLoan loan,
            final LoanTransactionType transactionType) {
        return transactionRepository.findActiveByTypeOrderByIdDesc(loan.getId(), transactionType).stream().findFirst();
    }
}
