{
    "name": "LoanTransactionEnumDataV1",
    "namespace": "org.apache.fineract.avro.loan.v1",
    "type": "record",
    "fields": [
        {
            "default": null,
            "name": "id",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "code",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "value",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "disbursement",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "repaymentAtDisbursement",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "repayment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "merchantIssuedRefund",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "payoutRefund",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "goodwillCredit",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "chargeRefund",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "contra",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "waiveInterest",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "waiveCharges",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "accrual",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "writeOff",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "recoveryRepayment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "initiateTransfer",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "approveTransfer",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "withdrawTransfer",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "rejectTransfer",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "chargePayment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "refund",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "refundForActiveLoans",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "creditBalanceRefund",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "chargeback",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "interestPaymentWaiver",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "chargeAdjustment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "chargeoff",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "downPayment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "reAge",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "reAmortize",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "accrualActivity",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "interestRefund",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "accrualAdjustment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "capitalizedIncome",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "capitalizedIncomeAmortization",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "capitalizedIncomeAdjustment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "capitalizedIncomeAmortizationAdjustment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "contractTermination",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "buyDownFee",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "buyDownFeeAdjustment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "buyDownFeeAmortization",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "buyDownFeeAmortizationAdjustment",
            "type": [
                "null",
                "boolean"
            ]
        }
    ]
}
