{
    "name": "WorkingCapitalLoanDelinquencyDataV1",
    "namespace": "org.apache.fineract.avro.workingcapitalloan.v1",
    "type": "record",
    "fields": [
        {
            "default": null,
            "name": "delinquencyStartType",
            "doc": "What starts the delinquency clock.",
            "type": [
                "null",
                "org.apache.fineract.avro.generic.v1.StringEnumOptionDataV1"
            ]
        },
        {
            "default": null,
            "name": "delinquencyStartDate",
            "type": [
                "null",
                "string"
            ]
        }
    ]
}
