{
    "name": "WorkingCapitalLoanDelinquencySchedulePeriodDataV1",
    "namespace": "org.apache.fineract.avro.workingcapitalloan.v1",
    "type": "record",
    "fields": [
        {
            "default": null,
            "name": "periodNumber",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "fromDate",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "toDate",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "expectedAmount",
            "type": [
                "null",
                "bigdecimal"
            ]
        },
        {
            "default": null,
            "name": "paidAmount",
            "type": [
                "null",
                "bigdecimal"
            ]
        },
        {
            "default": null,
            "name": "outstandingAmount",
            "type": [
                "null",
                "bigdecimal"
            ]
        },
        {
            "default": null,
            "name": "minPaymentCriteriaMet",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "delinquentDays",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "delinquentAmount",
            "type": [
                "null",
                "bigdecimal"
            ]
        },
        {
            "default": null,
            "name": "tags",
            "doc": "Active delinquency range tags currently applied to this schedule period.",
            "type": [
                "null",
                {
                    "type": "array",
                    "items": "org.apache.fineract.avro.workingcapitalloan.v1.WorkingCapitalLoanDelinquencyScheduleTagDataV1"
                }
            ]
        }
    ]
}
