{
    "name": "WorkingCapitalNearBreachDataV1",
    "namespace": "org.apache.fineract.avro.workingcapitalloan.v1",
    "type": "record",
    "fields": [
        {
            "default": null,
            "name": "id",
            "type": [
                "null",
                "long"
            ]
        },
        {
            "default": null,
            "name": "name",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "frequency",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "frequencyType",
            "type": [
                "null",
                "org.apache.fineract.avro.generic.v1.StringEnumOptionDataV1"
            ]
        },
        {
            "default": null,
            "name": "threshold",
            "type": [
                "null",
                "bigdecimal"
            ]
        }
    ]
}
