{
    "name": "WorkingCapitalLoanTransactionTypeDataV1",
    "namespace": "org.apache.fineract.avro.workingcapitalloan.v1",
    "type": "record",
    "fields": [
        {
            "default": null,
            "name": "id",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "code",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "value",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "disbursement",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "repayment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "payoutRefund",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "goodwillCredit",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "creditBalanceRefund",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "chargeAdjustment",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "repaymentType",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "chargeOff",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "writeOff",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "accrual",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "accrualAdjustment",
            "type": [
                "null",
                "boolean"
            ]
        }
    ]
}
