{
    "name": "WorkingCapitalLoanChargePaidByDataV1",
    "namespace": "org.apache.fineract.avro.workingcapitalloan.v1",
    "type": "record",
    "fields": [
        {
            "default": null,
            "name": "id",
            "type": [
                "null",
                "long"
            ]
        },
        {
            "default": null,
            "name": "amount",
            "type": [
                "null",
                "bigdecimal"
            ]
        },
        {
            "default": null,
            "name": "chargeId",
            "type": [
                "null",
                "long"
            ]
        },
        {
            "default": null,
            "name": "transactionId",
            "type": [
                "null",
                "long"
            ]
        },
        {
            "default": null,
            "name": "name",
            "type": [
                "null",
                "string"
            ]
        }
    ]
}
