{
    "name": "WorkingCapitalLoanBreachSchedulePeriodDataV1",
    "namespace": "org.apache.fineract.avro.workingcapitalloan.v1",
    "type": "record",
    "fields": [
        {
            "default": null,
            "name": "periodNumber",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "fromDate",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "toDate",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "numberOfDays",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "minPaymentAmount",
            "type": [
                "null",
                "bigdecimal"
            ]
        },
        {
            "default": null,
            "name": "outstandingAmount",
            "type": [
                "null",
                "bigdecimal"
            ]
        },
        {
            "default": null,
            "name": "paidAmount",
            "doc": "Amount already paid towards the minimum payment of this breach period.",
            "type": [
                "null",
                "bigdecimal"
            ]
        },
        {
            "default": null,
            "name": "nearBreach",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "breach",
            "type": [
                "null",
                "boolean"
            ]
        },
        {
            "default": null,
            "name": "reset",
            "type": [
                "null",
                "boolean"
            ]
        }
    ]
}
