{
    "name": "WorkingCapitalBreachDataV1",
    "namespace": "org.apache.fineract.avro.workingcapitalloan.v1",
    "type": "record",
    "fields": [
        {
            "default": null,
            "name": "id",
            "type": [
                "null",
                "long"
            ]
        },
        {
            "default": null,
            "name": "name",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "breachFrequency",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "breachFrequencyType",
            "type": [
                "null",
                "org.apache.fineract.avro.generic.v1.StringEnumOptionDataV1"
            ]
        },
        {
            "default": null,
            "name": "breachAmountCalculationType",
            "type": [
                "null",
                "org.apache.fineract.avro.generic.v1.StringEnumOptionDataV1"
            ]
        },
        {
            "default": null,
            "name": "breachAmount",
            "type": [
                "null",
                "bigdecimal"
            ]
        },
        {
            "default": null,
            "name": "breachGraceDays",
            "type": [
                "null",
                "int"
            ]
        },
        {
            "default": null,
            "name": "breachStartDate",
            "type": [
                "null",
                "string"
            ]
        },
        {
            "default": null,
            "name": "nearBreach",
            "type": [
                "null",
                "org.apache.fineract.avro.workingcapitalloan.v1.WorkingCapitalNearBreachDataV1"
            ]
        },
        {
            "default": null,
            "name": "breachSchedule",
            "doc": "Current breach schedule periods.",
            "type": [
                "null",
                {
                    "type": "array",
                    "items": "org.apache.fineract.avro.workingcapitalloan.v1.WorkingCapitalLoanBreachSchedulePeriodDataV1"
                }
            ]
        }
    ]
}
