name: Fineract Build Core

on:
  workflow_call:
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false

permissions:
  contents: read

jobs:
  build-core:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    env:
      TZ: Asia/Kolkata
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract
        with:
          cache-read-only: false

      - name: Pack workspace
        run: |
          tar --use-compress-program='gzip -9' -cf "${RUNNER_TEMP}/fineract-workspace.tar" -C "${GITHUB_WORKSPACE}" .

      - name: Upload workspace
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: fineract-workspace-${{ github.run_id }}
          path: ${{ runner.temp }}/fineract-workspace.tar
          retention-days: 1
          compression-level: 9

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results-build-core
          path: '**/build/reports/'
          if-no-files-found: ignore
          retention-days: 5
          compression-level: 9

      - name: Archive server logs
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: server-logs-build-core
          path: '**/build/cargo/'
          retention-days: 5
          compression-level: 9
