name: Fineract Quality Checks

on:
  workflow_call:
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false

permissions:
  contents: read

jobs:
  javadoc:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    env:
      TZ: Asia/Kolkata
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract

      - name: Generate Javadocs
        run: ./gradlew --no-daemon javadoc -x test -x cucumber -x doc -x buildJavaSdk

      - name: Archive Javadoc reports
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: javadoc-reports-quality-checks
          path: '**/build/docs/javadoc/'
          if-no-files-found: ignore
          retention-days: 1
          compression-level: 9

  checkstyle:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    env:
      TZ: Asia/Kolkata
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract

      - name: Run Checkstyle
        run: ./gradlew --no-daemon checkstyleMain checkstyleTest checkstyleJmh -x test -x cucumber -x doc -x javadoc -x javadocJar -x buildJavaSdk

      - name: Archive Checkstyle reports
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: checkstyle-reports-quality-checks
          path: '**/build/reports/checkstyle/'
          if-no-files-found: ignore
          retention-days: 1
          compression-level: 9

  rat:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    env:
      TZ: Asia/Kolkata
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract

      - name: Run RAT
        run: ./gradlew --no-daemon rat -x test -x cucumber -x doc -x javadoc -x javadocJar -x buildJavaSdk

      - name: Archive RAT reports
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: rat-reports-quality-checks
          path: '**/build/reports/rat/'
          if-no-files-found: ignore
          retention-days: 1
          compression-level: 9

  spotbugs:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    env:
      TZ: Asia/Kolkata
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract

      - name: Run SpotBugs
        run: ./gradlew --no-daemon spotbugsMain spotbugsTest -x test -x cucumber -x doc -x javadoc -x javadocJar -x buildJavaSdk

      - name: Archive SpotBugs reports
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: spotbugs-reports-quality-checks
          path: '**/build/reports/spotbugs/'
          if-no-files-found: ignore
          retention-days: 1
          compression-level: 9

  spotless:
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    env:
      TZ: Asia/Kolkata
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract

      - name: Run Spotless
        run: ./gradlew --no-daemon spotlessCheck -x test -x cucumber -x doc -x javadoc -x javadocJar -x buildJavaSdk
