name: Fineract Documentation build
on:
  workflow_call:
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true
      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
      - name: Configure vega-cli
        run: npm i -g vega-cli --unsafe
      - name: Install additional software
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript graphviz -y
      - name: Documentation build
        run: ./gradlew --no-daemon --console=plain doc -x buildJavaSdk
