name: Fineract Cucumber tests (without E2E tests)

on:
  workflow_call:
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false

permissions:
  contents: read

jobs:
  cucumber:
    runs-on: ubuntu-24.04
    timeout-minutes: 90

    env:
      TZ: Asia/Kolkata
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract

      - name: Run Cucumber
        run: ./gradlew --no-daemon cucumber -x :fineract-e2e-tests-runner:cucumber -x checkstyleJmh -x checkstyleMain -x checkstyleTest -x spotlessCheck -x spotlessApply -x spotbugsMain -x spotbugsTest -x javadoc -x javadocJar -x modernizer -x buildJavaSdk

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results-cucumber
          path: '**/build/reports/'
          if-no-files-found: ignore
          retention-days: 1
          compression-level: 9

      - name: Archive server logs
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: server-logs-cucumber
          path: '**/build/cargo/'
          retention-days: 1
          compression-level: 9
