name: Fineract Documentation build
on:
  workflow_call:
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Download workspace
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: fineract-workspace-${{ github.run_id }}
          path: .
      - name: Extract workspace
        run: tar -xf fineract-workspace.tar
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
      - name: Configure vega-cli
        run: npm i -g vega-cli --unsafe
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Install additional software
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript graphviz -y
      - name: Documentation build
        run: ./gradlew --no-daemon --console=plain doc -x buildJavaSdk
