name: Fineract Cargo & Unit- & Integration tests - PostgreSQL

on:
  workflow_call:
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false

permissions:
  contents: read

jobs:
  test:
    name: PostgreSQL Tests (Shard ${{ matrix.shard_index }} of ${{ matrix.total_shards }})
    runs-on: ubuntu-24.04
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        # Define the number of shards (1-based indexing)
        shard_index: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ]
        total_shards: [ 15 ]

    services:
      postgresql:
        image: postgres:18.3
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
        options: --health-cmd="pg_isready -q -d postgres -U root" --health-interval=5s --health-timeout=2s --health-retries=12

      mock-oauth2-server:
        image: ghcr.io/navikt/mock-oauth2-server:3.0.3
        ports:
          - 9000:9000
        env:
          SERVER_PORT: 9000
          JSON_CONFIG: '{ "interactiveLogin": true, "httpServer": "NettyWrapper", "tokenCallbacks": [ { "issuerId": "auth/realms/fineract", "tokenExpiry": 120, "requestMappings": [{ "requestParam": "scope", "match": "fineract", "claims": { "sub": "mifos", "scope": [ "test" ] } } ] } ] }'

    env:
      TZ: Asia/Kolkata
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      AWS_ENDPOINT_URL: http://localhost:4566
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: localstack
      AWS_REGION: us-east-1
      FINERACT_REPORT_EXPORT_S3_ENABLED: true
      FINERACT_REPORT_EXPORT_S3_BUCKET_NAME: fineract-reports

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract

      - name: Verify PostgreSQL connection
        run: |
          while ! pg_isready -d postgres -U root -h 127.0.0.1 -p 5432 ; do
            sleep 1
          done

      - name: Initialise databases
        run: |
          ./gradlew --no-daemon -q createPGDB -PdbName=fineract_tenants -x buildJavaSdk
          ./gradlew --no-daemon -q createPGDB -PdbName=fineract_default -x buildJavaSdk

      - name: Start LocalStack
        run: |
          docker run -d --name localstack -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack:2.1
          sleep 10
          docker exec localstack awslocal s3api create-bucket --bucket fineract-reports

      - name: Generate test class list
        run: |
          chmod +x scripts/split-tests.sh
          ./scripts/split-tests.sh ${{ matrix.total_shards }} ${{ matrix.shard_index }}
          cat "shard-tests_${{ matrix.shard_index }}.txt"

      - name: Run Gradle Task
        run: |
          set -e  # Fail the script if any command fails
          FAILED=0

          echo "Grouping test classes by module..."
          declare -A module_tests

          while IFS=, read -r module class; do
            module_tests["$module"]+="$class "
          done < "shard-tests_${{ matrix.shard_index }}.txt"

          for module in "${!module_tests[@]}"; do
            echo "::group::Running tests in $module"
            for class in ${module_tests[$module]}; do
              echo "  - $class"
            done

            # Build test args
            test_args=$(for class in ${module_tests[$module]}; do echo --tests "$class"; done | xargs)

            # Run test task for this module
            if ! ./gradlew --no-daemon "$module:test" $test_args -PdbType=postgresql -x checkstyleJmh -x checkstyleMain -x checkstyleTest -x spotlessCheck -x spotlessApply -x spotbugsMain -x spotbugsTest -x javadoc -x javadocJar -x modernizer -x buildJavaSdk ; then
              echo "::error::Tests failed in module $module"
              FAILED=1
            fi
            echo "::endgroup::"
          done

          # Exit with failure status if any test failed
          if [ "$FAILED" -eq 1 ]; then
            echo "::error::Some tests failed in this job"
            exit 1
          fi

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results-postgresql-shard-${{ matrix.shard_index }}-attempt-${{ github.run_attempt }}
          path: '**/build/reports/'
          retention-days: 1
          compression-level: 9

      - name: Archive server logs
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: server-logs-postgresql-shard-${{ matrix.shard_index }}-attempt-${{ github.run_attempt }}
          path: '**/build/cargo/'
          retention-days: 1
          compression-level: 9
