name: Fineract Liquibase Only mode - PostgreSQL

on:
  workflow_call:
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    services:
      postgresql:
        image: postgres:18.3
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: postgres
        options: --health-cmd="pg_isready -q -d postgres -U root" --health-interval=5s --health-timeout=2s --health-retries=12

    env:
      TZ: Asia/Kolkata
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Download workspace
        id: download-workspace
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        continue-on-error: true
        with:
          name: fineract-workspace-${{ github.run_id }}
          path: .

      - name: Extract workspace
        if: steps.download-workspace.outcome == 'success'
        run: tar -xf fineract-workspace.tar

      - name: Checkout
        if: steps.download-workspace.outcome != 'success'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build workspace fallback
        if: steps.download-workspace.outcome != 'success'
        uses: ./.github/actions/setup-and-build-fineract
        with:
          cache-read-only: false

      - name: Setup Gradle and Validate Wrapper
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          validate-wrappers: true

      - name: Verify PostgreSQL connection
        run: |
          while ! pg_isready -d postgres -U root -h 127.0.0.1 -p 5432 ; do
            sleep 1
          done

      - name: Initialise databases
        run: |
          ./gradlew --no-daemon -q createPGDB -PdbName=fineract_tenants -x buildJavaSdk
          ./gradlew --no-daemon -q createPGDB -PdbName=fineract_default -x buildJavaSdk

      - name: Run Fineract in Liquibase only mode
        env:
          FINERACT_DEFAULT_TENANTDB_CONN_PARAMS: ""
          FINERACT_DEFAULT_TENANTDB_DESCRIPTION: "Default Demo Tenant"
          FINERACT_DEFAULT_TENANTDB_HOSTNAME: "localhost"
          FINERACT_DEFAULT_TENANTDB_IDENTIFIER: "default"
          FINERACT_DEFAULT_TENANTDB_NAME: "fineract_default"
          FINERACT_DEFAULT_TENANTDB_PORT: "5432"
          FINERACT_DEFAULT_TENANTDB_PWD: "postgres"
          FINERACT_DEFAULT_TENANTDB_TIMEZONE: "Asia/Kolkata"
          FINERACT_DEFAULT_TENANTDB_UID: "root"
          FINERACT_HIKARI_DRIVER_SOURCE_CLASS_NAME: "org.postgresql.Driver"
          FINERACT_HIKARI_JDBC_URL: "jdbc:postgresql://localhost:5432/fineract_tenants"
          FINERACT_HIKARI_PASSWORD: "postgres"
          FINERACT_HIKARI_USERNAME: "root"
          SPRING_PROFILES_ACTIVE: "liquibase-only"
        run:
          ./gradlew --no-daemon fineract-provider:bootRun -x buildJavaSdk
