name: Fineract Publish to DockerHub
on:
  workflow_call:
    secrets:
      DEVELOCITY_ACCESS_KEY:
        required: false
      DOCKERHUB_USER:
        required: false
      DOCKERHUB_TOKEN:
        required: false
permissions:
  contents: read
jobs:
  build:
    if: >-
      ${{
        github.event_name == 'push' &&
        (
          github.ref_name == 'develop' ||
          github.ref_name == 'master' ||
          github.ref_name == 'main' ||
          startsWith(github.ref_name, 'release/') ||
          startsWith(github.ref_name, '1.')
        )
      }}
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract

      - name: Get Git Hashes
        run: |
          echo "short_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "long_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        id: git_hashes

      - name: Build the Apache Fineract image
        env:
          REF_NAME: ${{ github.ref_name }}
          SHORT_HASH: ${{ steps.git_hashes.outputs.short_hash }}
          LONG_HASH: ${{ steps.git_hashes.outputs.long_hash }}
        run:  |
          TAGS=$REF_NAME
          if [ "$TAGS" == "develop" ]; then
            TAGS="$TAGS,$SHORT_HASH,$LONG_HASH"
          else
            TAGS=$(git tag --points-at HEAD | grep -E '^1\.' | head -n 1 || true)
            if [ -z "$TAGS" ]; then
              echo "Skipping DockerHub publish because this run is not for develop or a 1.* tag."
              exit 0
            fi
          fi
          ./gradlew --no-daemon --console=plain :fineract-provider:jib -x test -x cucumber -x buildJavaSdk  \
            -Djib.to.auth.username=${{secrets.DOCKERHUB_USER}} \
            -Djib.to.auth.password=${{secrets.DOCKERHUB_TOKEN}} \
            -Djib.from.platforms=linux/amd64,linux/arm64 \
            -Djib.to.image=apache/fineract \
            -Djib.to.tags=$TAGS
