name: Fineract Sonarqube
on:
  workflow_call:
    secrets:
      SONAR_ORGANIZATION:
        required: false
      SONAR_PROJECT_KEY:
        required: false
      SONAR_HOST_URL:
        required: false
      SONARCLOUD_TOKEN:
        required: false
      DEVELOCITY_ACCESS_KEY:
        required: false
permissions:
  contents: read
jobs:
  build:
    if: >-
      ${{
        github.event_name == 'push' &&
        (
          github.ref_name == 'develop' ||
          github.ref_name == 'master' ||
          github.ref_name == 'main' ||
          startsWith(github.ref_name, 'release/') ||
          startsWith(github.ref_name, '1.')
        )
      }}
    runs-on: ubuntu-24.04
    timeout-minutes: 90
    env:
        TZ: Asia/Kolkata
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
        JAVA_BINARIES: .
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true
      - name: Build Fineract
        uses: ./.github/actions/setup-and-build-fineract
      - name: Sonar
        run: ./gradlew --no-daemon --console=plain -Dsonar.verbose=true -Dsonar.token=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.java.binaries=$JAVA_BINARIES --info --stacktrace sonar -x buildJavaSdk
